name: Update-Checker

on:
  push:
    branches:
      - main

jobs:
  run-node-script:
    runs-on: ubuntu-22.04

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Passe die Node.js-Version an deine Anforderungen an

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run a custom Node.js script
      - name: Run Update Checker
        run: node Update[Payloader]/update-timer.js

      - name: Run Git add .
        run: git add .

      - name: Run git commit
      run: git commit -m "auto-update"

      - name: Run git push 
      run: git push origin main