name: Update-Checker

on:
  push:
    branches:
      - main

jobs:
  run-node-script:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  
     
      - name: Install Dependencies
        run: npm install

     
      - name: Run Update Checker
        run: node "Update[Payloader]/update-timer.js"

      - name: Configure Git Identity
        run: |
          git config --global user.name "TristanSimonDev"
          git config --global user.email "simontristandev@gmail.com"


      - name: Stage changes
        run: git add .

      - name: Commit changes
        run: git commit --allow-empty -m "auto-update" || echo "No changes to commit"

      - name: Push changes
        env:
          GH_TOKEN: ${{ secrets.key }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/TristanSimonDev/InfoProjekt-Website-Linux.git
          git push origin main
