name: Update-Checker

on:
  push:
    branches:
      - main

jobs:
  run-node-script:
    runs-on: ubuntu-22.04

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Passe die Node.js-Version an deine Anforderungen an

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run a custom Node.js script
      - name: Run Update Checker
        run: node "Update[Payloader]/update-timer.js"

      # Stage changes (git add)
      - name: Stage changes
        run: git add .

      # Commit changes
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git commit -m "auto-update" || echo "No changes to commit"

      # Push changes
      - name: Push changes
        run: git push origin main
